student/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^new/$', views.student_create, name='new'),
    url(r'^csv/$', views.student_create_csv, name='csv'),
    url(r'^search/$', views.student_search, name='search'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.student_update, name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.StudentDelete.as_view(), name='delete'),
]

waise/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^student/', include(('student.urls', 'student'), namespace='student')),
    path('faculty/', include('faculty.urls')),

]

student/models.py
import datetime

from django.db import models
from django.urls import reverse

from faculty.models import Faculty

DEPARTMENTS = (('CS', 'Computer Science And Engineering'), ('IT', 'Information Technology'),
               ('EEE', 'Electrical & Electronics Engineering'), ('EC', 'Electronics & Communication'),
               ('SFE', 'Safety & Fire Engineering'), ('CE', 'Civil Engineering'),
               ('ME', 'Mechanical Engineering'))

SEMESTERS = (('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'),
             ('8', 'S8'))

SECTION = (('A', 'A'), ('B', 'B'))

GENDER = (('M', 'Male'), ('F', 'Female'))

SUB_TYPES = (('T', 'Theory'), ('L', 'Practical'), ('P', 'Project'))

EXAMS = (('Internal', 'Internal'), ('External', 'External'))


def student_photo_location(instance, filename):
    extension = filename.split('.')[-1]
    return f'student/reg_photos/{instance.regno}.{extension}'


class Student(models.Model):
    STATUS = (('Active', 'Currently Studying'), ('Pass out', 'Course Completed'),
              ('Drop out', 'Drop out '))

    BLOODGROUPS = (('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'),
                   ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'),
                   ('O+ve', 'O+ve'), ('O-ve', 'O-ve'),)

    limit = datetime.datetime.today().year + 1
    YEARS = tuple([(x, x) for x in range(2015, 2025)])

    ADMISSION_TYPE = (('Regular', 'Regular'), ('Lateral Entry', 'Lateral Entry'))

    regno = models.IntegerField(primary_key=True, verbose_name='Register Number')

    # Bio Data.
    name = models.CharField(max_length=30, verbose_name='Name')
    gender = models.CharField(max_length=6, choices=GENDER, default='M')
    studentcontactno = models.CharField(max_length=15, verbose_name='Students Contact No', null=True, blank=True)
    emailid = models.CharField(max_length=80, verbose_name=u'Email Id', null=True, blank=True)
    dateofbirth = models.DateField(verbose_name='Date of birth', default='2000-01-01')
    permanentaddress = models.CharField(max_length=150, verbose_name='Permanent Address', null=True, blank=True)
    temporaryaddress = models.CharField(max_length=150, verbose_name='Temporary Address', null=True, blank=True)
    category = models.CharField(max_length=20, default='General')
    specialreservation = models.CharField(max_length=30, verbose_name='Special Reservation', null=True, blank=True)
    religion = models.CharField(max_length=15, null=True, blank=True)
    bloodgroup = models.CharField(max_length=6, verbose_name='Blood Group', choices=BLOODGROUPS, null=True, blank=True)
    personwithdisabilities = models.CharField(max_length=40, verbose_name='Person with Disabilities', null=True,
                                              blank=True)

    # Current student details.
    branch = models.CharField(max_length=15, choices=DEPARTMENTS)
    cursem = models.CharField(max_length=2, choices=SEMESTERS, verbose_name='Semester')
    section = models.CharField(max_length=1, choices=SECTION)
    photo = models.FileField(upload_to=student_photo_location, null=True, blank=True)

    # Admission details.
    status = models.CharField(max_length=20, choices=STATUS, default='Active')
    join = models.IntegerField(choices=YEARS, verbose_name='Year Of Join')
    admissionno = models.IntegerField(verbose_name='Admission Number', default='0')
    admtype = models.CharField(max_length=20, choices=ADMISSION_TYPE, default='Regular')

    # Academic history.
    catrank = models.IntegerField(verbose_name='CAT Rank', default='0')
    tenboard = models.CharField(max_length=20, verbose_name='10th Board', null=True, blank=True)
    tenregisterno = models.CharField(max_length=20, verbose_name='10th Register No', null=True, blank=True)
    tenmarks = models.IntegerField(verbose_name='10th Marks', null=True, blank=True)
    tenpercentage = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='10th Percentage', null=True,
                                        blank=True)
    tenyear = models.IntegerField(default='0')
    qualifyingboard = models.CharField(max_length=20, verbose_name='Qualifying Board', null=True, blank=True)
    qualifyingregisterno = models.IntegerField(verbose_name='Qualifying Register No', null=True, blank=True)
    qualifyingmarks = models.IntegerField(verbose_name='Qualifying Marks', null=True, blank=True)
    qualifyingpercentage = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Qualifying Percentage',
                                               null=True, blank=True)
    qualifyingyear = models.IntegerField(verbose_name='Qualifying Year', null=True, blank=True)

    # Guardian details.
    parentorguardianname = models.CharField(max_length=50, verbose_name='Parent/Guardians Name', null=True, blank=True)
    parentorguardianoccupation = models.CharField(max_length=25, verbose_name='Parent/Guardians Occupation', null=True,
                                                  blank=True)
    parentorguardiancontactno = models.CharField(max_length=15, verbose_name='Parent/Guardians Contact No', null=True,
                                                 blank=True)
    parentorguardianemailid = models.CharField(max_length=50, verbose_name='Parent/Guardians Email Id', null=True,
                                               blank=True)

    # Current Academic details.
    miniproject = models.CharField(max_length=100, verbose_name='Mini Project', null=True, blank=True)
    miniprojectguide = models.CharField(max_length=25, verbose_name='Mini Project Guide', null=True, blank=True)
    mainproject = models.CharField(max_length=100, verbose_name='Main Project', null=True, blank=True)
    mainprojectguide = models.CharField(max_length=25, verbose_name='Main Project Guide', null=True, blank=True)
    behaviour = models.CharField(max_length=100, default='Good', null=True, blank=True)

    # Function to redirect to the homepage after adding to db.
    def get_absolute_url(self):
        return reverse('student:index', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.regno) + ': ' + str(self.name)

    class Meta:
        ordering = ('regno',)  # 'ordering' must be a tuple or list (even if you want to order by only one field).


class Syllabus(models.Model):
    YEARS = []
    limit = datetime.datetime.today().year + 10
    for x in range(2010, limit):
        YEARS.append((x, x))

    year = models.PositiveIntegerField(choices=YEARS)
    dept = models.CharField(max_length=60, choices=DEPARTMENTS, verbose_name='Department')

    def __str__(self):
        return str(self.year)

    class Meta:
        ordering = ('year',)


class Subject(models.Model):
    syllabus = models.ForeignKey(Syllabus, on_delete=models.CASCADE, default='1')
    code = models.CharField(primary_key=True, max_length=15)
    name = models.CharField(max_length=70)
    branch = models.CharField(max_length=70, choices=DEPARTMENTS)
    sem = models.CharField(max_length=2, choices=SEMESTERS)
    type = models.CharField(max_length=15, choices=SUB_TYPES)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ('code',)


class MarkList(models.Model):
    CHANCES = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'))

    YEARS = []
    limit = datetime.datetime.today().year + 10
    for x in range(2015, limit):
        YEARS.append((x, x))

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    branch = models.CharField(max_length=70, choices=DEPARTMENTS)
    sem = models.CharField(max_length=2, choices=SEMESTERS)
    section = models.CharField(max_length=1, choices=SECTION)
    type = models.CharField(max_length=9, choices=EXAMS, default='Internal')
    batch_join_year = models.IntegerField(choices=YEARS, default='0')
    chance = models.IntegerField(default='0', choices=CHANCES)

    def __str__(self):
        return str(self.student) + ' S' + str(self.sem)

    class Meta:
        ordering = ('student',)


class SubjectMarks(models.Model):
    mark_list = models.ForeignKey(MarkList, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    marks = models.SmallIntegerField(default='0')
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.marks)

    class Meta:
        ordering = ('mark_list',)

student/forms.py
import datetime

from django import forms
from .models import Student


class StudentModelForm(forms.ModelForm):
    end_limit = datetime.datetime.today().year + 1
    start_limit = datetime.datetime.today().year - 6
    YEAR_RANGE = tuple([(x, x) for x in range(start_limit, end_limit)])

    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[A-Za-z ]+'}), label='Student Name')
    dateofbirth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    qualifyingyear = forms.CharField(widget=forms.Select(choices=YEAR_RANGE), label='Qualifying Year')
    tenyear = forms.CharField(widget=forms.Select(choices=YEAR_RANGE), label='10th Qualifying Year')
    permanentaddress = forms.CharField(widget=forms.Textarea())
    temporaryaddress = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['branch']

    def __init__(self, *args, **kwargs):
        super(StudentModelForm, self).__init__(*args, **kwargs)
        self.fields['permanentaddress'].widget.attrs['style'] = 'width:400px;height:180px;margin-bottom:10px;'
        self.fields['temporaryaddress'].widget.attrs['style'] = 'width:400px;height:180px;margin-bottom:10px;'
        self.fields['status'].widget.attrs['style'] = 'width:200px;'
        self.fields['religion'].widget.attrs['style'] = 'width:200px;'
        self.fields['studentcontactno'].widget.attrs['style'] = 'width:150px;'

        self.fields['tenyear'].label = '10th Year of Passout'
        self.fields['cursem'].label = 'Semester'
        self.fields['join'].label = 'Year of Join'
        self.fields['admtype'].label = 'Admission Type'
        self.fields['permanentaddress'].label = 'Permanent Address'
        self.fields['temporaryaddress'].label = 'Temporary Address'
        self.fields['dateofbirth'].label = 'Date of Birth'


class StudentCsvForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ('photo',)


class StudentUpdateForm(forms.ModelForm):
    regno = forms.IntegerField(disabled=True, widget=forms.TextInput(attrs={'size': 2}))
    permanentaddress = forms.CharField(widget=forms.Textarea())
    temporaryaddress = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Student
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(StudentUpdateForm, self).__init__(*args, **kwargs)
        self.fields['permanentaddress'].widget.attrs['style'] = 'width:400px;height:180px'
        self.fields['temporaryaddress'].widget.attrs['style'] = 'width:400px;height:180px'
        self.fields['status'].widget.attrs['style'] = 'width:180px;'
        self.fields['branch'].widget.attrs['style'] = 'width:320px;'
        self.fields['regno'].label = 'Register Number'
        self.fields['permanentaddress'].label = 'Permanent Address'
        self.fields['temporaryaddress'].label = 'Temporary Address'
        self.fields['name'].label = 'Student Name'
        self.fields['cursem'].label = 'Semester'
        self.fields['join'].label = 'Year of Join'
        self.fields['admtype'].label = 'Admission Type'

student/views.py
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView

from student.filters import StudentFilter
from student.forms import StudentModelForm, StudentCsvForm, StudentUpdateForm
from student.models import Student


# TODO: Add user's dept to the queries

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def student_create(request):
    student = StudentModelForm(request.POST or None)

    if student.is_valid():
        instance = student.save(commit=False)
        instance.branch = 'CS'
        # instance.branch = request.user.dept
        instance.save()

        return redirect('student:search')

    context = {
        "form": student,
        "title": 'Add Student',
    }

    return render(request, 'student/student_form.html', context)


def student_create_csv(request):
    if "GET" == request.method:
        data = {
            'title': 'Student CSV'
        }
        return render(request, "student/student_csv.html", data)

    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            return HttpResponseRedirect(reverse("student:csv"))
            # if file is too large, return
        if csv_file.multiple_chunks():
            return HttpResponseRedirect(reverse("student:csv"))

        data = csv.DictReader(csv_file.read().decode('utf-8').splitlines())

        for data_dict in data:

            try:
                form = StudentCsvForm(data_dict)
                # print("-----------", data_dict)
                if form.is_valid():
                    form.save()
                else:
                    lst = []
                    for i in form.errors:
                        lst.append(str((i, form.errors[i])) + ' | ' + str(data_dict['name']))

                    print(lst)
                    # return render(request, "student/faculty_attendance_main.html", {'obj': lst})
            except Exception as e:
                print(repr(e))
                pass

    except Exception as e:
        print(repr(e))

    return HttpResponseRedirect(reverse("student:index"))


def student_search(request):
    if request.method == 'GET':
        student_list = Student.objects.all().order_by('regno')
        student_filter = StudentFilter(request.GET, queryset=student_list)
        return render(request, 'student/student_list.html', {'filter': student_filter, 'title': 'Student Search'})


def student_update(request, pk):
    instance = get_object_or_404(Student, regno=pk)
    student = StudentUpdateForm(request.POST or None, request.FILES or None, instance=instance)
    if student.is_valid():
        instance = student.save(commit=False)
        instance.save()

        return redirect('student:search')
    context = {
        "form": student,
        "title": 'Edit Student',
    }

    return render(request, 'student/student_form.html', context)


class StudentDelete(DeleteView):
    model = Student

    def get_success_url(self):
        url = self.request.GET['next']
        params = url.split('?')[1]
        base = reverse('student:search')
        url = f'{base}?{params}'
        return url

templates/student/empty.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}

{% block navbar %} Hai. I'll add the navbar shortly. {% endblock %}

{% block form %}


{% endblock %}

templates/student/student_confirm_delete.html
<!--this template is used for deleteview-->
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}

{% block navbar %} Hai. I'll add the navbar shortly. {% endblock %}

{% block form %}
<section style="margin-left:250px">
    <h1>Delete Student</h1>

    <p>Are you sure you want to delete the student: {{ student }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete."/>
    </form>

</section>
{% endblock %}

templates/student/student_csv.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}

{% block navbar %} Hai. I'll add the navbar shortly. {% endblock %}

{% block form %}
<section style="margin-left:75px">

    <h3>Note : CSV file should have the fields in the format given below:</h3>
    <ul>
        regno, name, branch, cursem, join, section, status, parent, admtype, gender, admissionno, permanentaddress,
        temporaryaddress, dateofbirth, category, emailid, personwithdisabilities, catrank, religion, bloodgroup,
        parentorguardianname, parentorguardianoccupation, parentorguardiancontactno, parentorguardianemailid,
        miniproject, miniprojectguide, mainproject, mainprojectguide, behaviour, studentcontactno, studentemailid,
        tenboard, tenregisterno, tenmarks, tenpercentage, tenyear, qualifyingboard, qualifyingregisterno,
        qualifyingmarks, qualifyingpercentage,qualifyingyear,specialreservation
    </ul>
    <h3> Status field must given the exact value as given below:</h3>
    <ul>
        The status field should have the value 'Active' for Currently Studying students and 'Pass out' for those who
        have completed the course and 'Drop out' for those who have discontinued their studies.
    </ul>

    <h3>Optional fields</h3>
    <ul>
        parentorguardianemailid,personwithdisabilities,miniproject,miniprojectguide,mainproject,
        mainprojectguide,specialreservation.
    </ul>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        <button type="submit">Submit</button>

    </form>

</section>
{% endblock %}

templates/student/student_form.html
<!--the name of this html file is given as the format { <model name>_form.html }-->
<!--<model name> should be in lowercase-->
<!--eg: Student then the form.html filename is student_form.html-->
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}

{% block navbar %} Hai. I'll add the navbar shortly. {% endblock %}

templates/student/student_list.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}

{% block navbar %} Hai. I'll add the navbar shortly. {% endblock %}

{% block form %}
<section>
    <div style="text-align: center;margin-left: 50px; " class="4u 12u$(medium)">
        <form method="get">

            <table style="width:700px;">
                <tr>
                    <th style="text-align:center;">

                        <label style="font-size: medium;font-family:Arial">{{ filter.form.cursem.label }}</label>
                    </th>

                    <th style="text-align:center;">
                        <label style="font-size: medium;font-family:Arial">{{ filter.form.join.label }}</label>
                    </th>

                    <th style="text-align:center;">
                        <label style="font-size: medium;font-family:Arial">{{ filter.form.regno.label }}</label>
                    </th>


                </tr>
                <tr>
                    <td>
                        {{ filter.form.cursem }}
                    </td>

                    <td>
                        {{ filter.form.join }}
                    </td>

                    <td>
                        {{ filter.form.regno }}
                    </td>

                </tr>

            </table>

            <button type="submit" name="submit" style="margin-left:300px;">Search</button>
        </form>
    </div>
    </form>


    {% if request.GET %}
    <ul>
        <table id="tables" class="table table-striped table-bordered dt-responsive dataTables_wrapper"
               cellspacing="0">

            <tr>
                <th>
                    <label style="font-size: medium;font-family:Arial">Register Number</label>
                </th>

                <th>
                    <label style="font-size: medium;font-family:Arial">Student Name </label>
                </th>

                <th>
                    <label style="font-size: medium;font-family:Arial">Branch</label>
                </th>

                <th>
                    <label style="font-size: medium;font-family:Arial">Semester</label>
                </th>

                <th>
                    <label style="font-size: medium;font-family:Arial">Joining Year</label>
                </th>

                <th>
                    <label style="font-size: medium;font-family:Arial"></label>
                </th>
            </tr>


            {% for student in filter.qs %}
            <tr>
                <td>
                    <label style="font-size: medium;font-family:Arial"><a
                            href="{% url 'student:update' student.regno %}">{{ student.regno }}</a>
                    </label>
                </td>

                <td>
                    <label style="font-size: medium;font-family:Arial">{{ student.name }} </label>
                </td>


                <td>
                    <label style="font-size: medium;font-family:Arial">{{ student.branch }} </label>
                </td>
                <td>
                    <label style="font-size: medium;font-family:Arial">{{ student.cursem }} </label>
                </td>
                <td>
                    <label style="font-size: medium;font-family:Arial">{{ student.join }} </label>
                </td>
                <td>
                    <label style="font-size: medium;font-family:Arial"><a
                            href="{% url 'student:delete' student.regno %}?next={{ request.get_full_path|urlencode }}">Delete</a>
                    </label>
                </td>
            </tr>

            {% empty %}
            <p style="font-weight: bold">Sorry no data found with the given filter </p>
            {% endfor %}
        </table>
    </ul>
    {% endif %}

</section>
{% endblock %}